import type { ThemeConfig, BgPreset } from './themeTypes';

// --- Default Theme Config ----------------------------------------------------
// This is the exact current look of MT-Vocab � always the safe fallback

export const DEFAULT_THEME_CONFIG: ThemeConfig = {
  colors: {
    primary:    '#6366f1',
    secondary:  '#a855f7',
    accent:     '#10b981',
    background: '#09090f',
    surface:    '#12121c',
    card:       'rgba(255,255,255,0.03)',
    text:       '#ffffff',
    textMuted:  'rgba(255,255,255,0.55)',
    border:     'rgba(255,255,255,0.10)',
    success:    '#10b981',
    warning:    '#f59e0b',
    danger:     '#ef4444',
  },
  background: {
    type: 'preset',
    color: '#09090f',
    gradient: 'midnight',
    preset: 'default',
  },
  typography: {
    fontFamily: 'inter',
    sizeScale: 'normal',
    weight: 'medium',
  },
  buttons: {
    style: 'rounded',
    shadow: 'soft',
  },
  cards: {
    style: 'glass',
    radius: 'large',
    shadow: 'soft',
  },
  navbar: {
    style: 'glass',
    blur: 'medium',
    border: 'thin',
  },
  borders: {
    style: 'thin',
    radius: 'large',
  },
  shadows: 'soft',
  spacing: {
    density: 'normal',
  },
  effects: {
    animations: 'normal',
    glass: 'soft',
    hover: 'normal',
  },
};

// --- Preset Themes ------------------------------------------------------------

export interface PresetTheme {
  id: BgPreset;
  name: string;
  emoji: string;
  config: ThemeConfig;
}

const base = (overrides: Partial<Omit<ThemeConfig, 'background' | 'colors'>> & { colors?: Partial<ThemeConfig['colors']>; background?: Partial<ThemeConfig['background']> }): ThemeConfig => ({
  ...DEFAULT_THEME_CONFIG,
  ...overrides,
  colors: { ...DEFAULT_THEME_CONFIG.colors, ...overrides.colors },
  background: { ...DEFAULT_THEME_CONFIG.background, ...overrides.background },
});

export const PRESET_THEMES: PresetTheme[] = [
  {
    id: 'default',
    name: 'Default',
    emoji: '?',
    config: DEFAULT_THEME_CONFIG,
  },
  {
    id: 'ocean',
    name: 'Ocean',
    emoji: '??',
    config: base({
      colors: {
        primary: '#0ea5e9',
        secondary: '#06b6d4',
        accent: '#22d3ee',
        background: '#020c18',
        surface: '#041424',
        card: 'rgba(14,165,233,0.06)',
        text: '#e0f2fe',
        textMuted: 'rgba(224,242,254,0.5)',
        border: 'rgba(14,165,233,0.15)',
        success: '#10b981', warning: '#f59e0b', danger: '#ef4444',
      },
      background: { type: 'preset', color: '#020c18', gradient: 'ocean', preset: 'ocean' },
    }),
  },
  {
    id: 'space',
    name: 'Space',
    emoji: '??',
    config: base({
      colors: {
        primary: '#8b5cf6',
        secondary: '#a78bfa',
        accent: '#c4b5fd',
        background: '#030014',
        surface: '#0a0120',
        card: 'rgba(139,92,246,0.06)',
        text: '#ede9fe',
        textMuted: 'rgba(237,233,254,0.5)',
        border: 'rgba(139,92,246,0.15)',
        success: '#10b981', warning: '#f59e0b', danger: '#ef4444',
      },
      background: { type: 'preset', color: '#030014', gradient: 'purple', preset: 'space' },
    }),
  },
  {
    id: 'forest',
    name: 'Forest',
    emoji: '??',
    config: base({
      colors: {
        primary: '#22c55e',
        secondary: '#16a34a',
        accent: '#86efac',
        background: '#021008',
        surface: '#041a0e',
        card: 'rgba(34,197,94,0.06)',
        text: '#dcfce7',
        textMuted: 'rgba(220,252,231,0.5)',
        border: 'rgba(34,197,94,0.15)',
        success: '#22c55e', warning: '#f59e0b', danger: '#ef4444',
      },
      background: { type: 'preset', color: '#021008', gradient: 'forest', preset: 'forest' },
    }),
  },
  {
    id: 'sunset',
    name: 'Sunset',
    emoji: '??',
    config: base({
      colors: {
        primary: '#f97316',
        secondary: '#ef4444',
        accent: '#fbbf24',
        background: '#160800',
        surface: '#1f0f00',
        card: 'rgba(249,115,22,0.06)',
        text: '#fff7ed',
        textMuted: 'rgba(255,247,237,0.5)',
        border: 'rgba(249,115,22,0.15)',
        success: '#10b981', warning: '#fbbf24', danger: '#ef4444',
      },
      background: { type: 'gradient', color: '#160800', gradient: 'sunset', preset: 'sunset' },
      effects: { animations: 'playful', glass: 'soft', hover: 'playful' },
    }),
  },
  {
    id: 'midnight',
    name: 'Midnight',
    emoji: '??',
    config: base({
      colors: {
        primary: '#eab308',
        secondary: '#ca8a04',
        accent: '#fde047',
        background: '#000000',
        surface: '#080808',
        card: 'rgba(234,179,8,0.04)',
        text: '#fefce8',
        textMuted: 'rgba(254,252,232,0.4)',
        border: 'rgba(234,179,8,0.12)',
        success: '#10b981', warning: '#eab308', danger: '#ef4444',
      },
      background: { type: 'color', color: '#000000', gradient: 'midnight', preset: 'midnight' },
      cards: { style: 'solid', radius: 'medium', shadow: 'medium' },
    }),
  },
  {
    id: 'minimal',
    name: 'Minimal',
    emoji: '⚪',
    config: base({
      colors: {
        primary: '#64748b',
        secondary: '#94a3b8',
        accent: '#cbd5e1',
        background: '#0f172a',
        surface: '#1e293b',
        card: 'rgba(255,255,255,0.04)',
        text: '#f1f5f9',
        textMuted: 'rgba(241,245,249,0.4)',
        border: 'rgba(255,255,255,0.08)',
        success: '#10b981', warning: '#f59e0b', danger: '#ef4444',
      },
      background: { type: 'color', color: '#0f172a', gradient: 'midnight', preset: 'minimal' },
      effects: { animations: 'subtle', glass: 'off', hover: 'minimal' },
      cards: { style: 'minimal', radius: 'medium', shadow: 'none' },
    }),
  },
  {
    id: 'kids',
    name: 'Kids (Bolalar)',
    emoji: '🌈',
    config: base({
      colors: {
        primary: '#ff6b35',
        secondary: '#f59e0b',
        accent: '#10b981',
        background: '#0a1428',
        surface: '#0f1d38',
        card: 'rgba(15,29,56,0.65)',
        text: '#ffffff',
        textMuted: 'rgba(255,255,255,0.7)',
        border: 'rgba(255,107,53,0.3)',
        success: '#10b981', warning: '#f59e0b', danger: '#ef4444',
      },
      background: {
        type: 'image',
        imageUrl: '/themes/kids-bg.jpg',
        imagePosition: 'center',
        imageSize: 'cover',
        overlay: 'soft',
        blur: 'none',
      },
      typography: { fontFamily: 'nunito', sizeScale: 'normal', weight: 'bold' },
      buttons: { style: 'pill', shadow: 'glow' },
      cards: { style: 'glass', radius: 'xl', shadow: 'strong', blur: 'medium' },
      effects: { animations: 'playful', glass: 'soft', hover: 'playful' },
    }),
  },
  {
    id: 'teen',
    name: 'Teen (O\'smirlar)',
    emoji: '🎧',
    config: base({
      colors: {
        primary: '#8b5cf6',
        secondary: '#a855f7',
        accent: '#c084fc',
        background: '#0f0a1e',
        surface: '#181030',
        card: 'rgba(24,16,48,0.60)',
        text: '#ede9fe',
        textMuted: 'rgba(237,233,254,0.6)',
        border: 'rgba(139,92,246,0.35)',
        success: '#10b981', warning: '#f59e0b', danger: '#ef4444',
      },
      background: {
        type: 'image',
        imageUrl: '/themes/teen-bg.jpg',
        imagePosition: 'center',
        imageSize: 'cover',
        overlay: 'light',
        blur: 'none',
      },
      typography: { fontFamily: 'inter', sizeScale: 'normal', weight: 'medium' },
      buttons: { style: 'rounded', shadow: 'glow' },
      cards: { style: 'glass', radius: 'large', shadow: 'strong', blur: 'medium' },
      effects: { animations: 'normal', glass: 'soft', hover: 'normal' },
    }),
  },
  {
    id: 'adult',
    name: 'Adult (Kattalar)',
    emoji: '🏔️',
    config: base({
      colors: {
        primary: '#3b82f6',
        secondary: '#60a5fa',
        accent: '#38bdf8',
        background: '#0a1428',
        surface: '#101d36',
        card: 'rgba(16,29,54,0.65)',
        text: '#f0f9ff',
        textMuted: 'rgba(240,249,255,0.6)',
        border: 'rgba(59,130,246,0.25)',
        success: '#10b981', warning: '#f59e0b', danger: '#ef4444',
      },
      background: {
        type: 'image',
        imageUrl: '/themes/adult-bg.jpg',
        imagePosition: 'center',
        imageSize: 'cover',
        overlay: 'soft',
        blur: 'none',
      },
      typography: { fontFamily: 'inter', sizeScale: 'normal', weight: 'medium' },
      buttons: { style: 'soft', shadow: 'soft' },
      cards: { style: 'glass', radius: 'medium', shadow: 'medium', blur: 'medium' },
      effects: { animations: 'subtle', glass: 'soft', hover: 'normal' },
    }),
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    emoji: '⚡',
    config: base({
      colors: {
        primary: '#00f0ff',
        secondary: '#a855f7',
        accent: '#ff007f',
        background: '#0b001a',
        surface: '#14002e',
        card: 'rgba(20,0,46,0.60)',
        text: '#f0f8ff',
        textMuted: 'rgba(240,248,255,0.6)',
        border: 'rgba(0,240,255,0.30)',
        success: '#00ff9d', warning: '#ffb703', danger: '#ff0055',
      },
      background: { type: 'preset', color: '#0b001a', gradient: 'purple', preset: 'cyberpunk' },
      typography: { fontFamily: 'poppins', sizeScale: 'normal', weight: 'bold' },
      buttons: { style: 'rounded', shadow: 'glow' },
      cards: { style: 'glass', radius: 'large', shadow: 'glow', blur: 'strong' },
      navbar: { style: 'glass', blur: 'strong', border: 'glow' },
      effects: { animations: 'playful', glass: 'strong', hover: 'playful' },
    }),
  },
  {
    id: 'matrix',
    name: 'Emerald Matrix',
    emoji: '🟢',
    config: base({
      colors: {
        primary: '#10b981',
        secondary: '#059669',
        accent: '#00ff9d',
        background: '#020f08',
        surface: '#051f12',
        card: 'rgba(5,31,18,0.65)',
        text: '#ecfdf5',
        textMuted: 'rgba(236,253,245,0.6)',
        border: 'rgba(16,185,129,0.30)',
        success: '#10b981', warning: '#f59e0b', danger: '#ef4444',
      },
      background: { type: 'preset', color: '#020f08', gradient: 'forest', preset: 'matrix' },
      typography: { fontFamily: 'inter', sizeScale: 'normal', weight: 'medium' },
      buttons: { style: 'rounded', shadow: 'glow' },
      cards: { style: 'glass', radius: 'large', shadow: 'glow', blur: 'medium' },
      navbar: { style: 'glass', blur: 'medium', border: 'thin' },
      effects: { animations: 'normal', glass: 'soft', hover: 'normal' },
    }),
  },
  {
    id: 'sunset_gold',
    name: 'Sunset Gold',
    emoji: '🔥',
    config: base({
      colors: {
        primary: '#f59e0b',
        secondary: '#ea580c',
        accent: '#fbbf24',
        background: '#160800',
        surface: '#240d00',
        card: 'rgba(36,13,0,0.65)',
        text: '#fffbeb',
        textMuted: 'rgba(255,251,235,0.6)',
        border: 'rgba(245,158,11,0.30)',
        success: '#10b981', warning: '#f59e0b', danger: '#ef4444',
      },
      background: { type: 'gradient', color: '#160800', gradient: 'sunset', preset: 'sunset_gold' },
      typography: { fontFamily: 'poppins', sizeScale: 'normal', weight: 'medium' },
      buttons: { style: 'pill', shadow: 'glow' },
      cards: { style: 'glass', radius: 'xl', shadow: 'glow', blur: 'medium' },
      navbar: { style: 'glass', blur: 'medium', border: 'glow' },
      effects: { animations: 'playful', glass: 'soft', hover: 'playful' },
    }),
  },
  {
    id: 'midnight_velvet',
    name: 'Midnight Velvet',
    emoji: '💎',
    config: base({
      colors: {
        primary: '#6366f1',
        secondary: '#818cf8',
        accent: '#38bdf8',
        background: '#04040a',
        surface: '#090a14',
        card: 'rgba(9,10,20,0.60)',
        text: '#f8fafc',
        textMuted: 'rgba(248,250,252,0.55)',
        border: 'rgba(99,102,241,0.22)',
        success: '#10b981', warning: '#f59e0b', danger: '#ef4444',
      },
      background: { type: 'color', color: '#04040a', gradient: 'midnight', preset: 'midnight_velvet' },
      typography: { fontFamily: 'inter', sizeScale: 'normal', weight: 'medium' },
      buttons: { style: 'rounded', shadow: 'soft' },
      cards: { style: 'glass', radius: 'large', shadow: 'glow', blur: 'strong' },
      navbar: { style: 'glass', blur: 'strong', border: 'thin' },
      effects: { animations: 'normal', glass: 'strong', hover: 'normal' },
    }),
  },
];

export const getPresetById = (id: BgPreset): PresetTheme | undefined =>
  PRESET_THEMES.find(p => p.id === id);
