/**
 * emojiMap.ts
 * Static dictionary of English words → emojis.
 * Used first (zero cost, zero latency).
 * Gemini emoji suggestions used only for words NOT in this map.
 *
 * SAFETY: Never force an emoji if meaning is unclear (entry = '').
 * Emoji is metadata only — never replaces vocabulary.
 */

const EMOJI_MAP: Record<string, string> = {
  // Nature / Weather
  thunder: '🌩️',
  lightning: '⚡',
  rain: '🌧️',
  snow: '❄️',
  sun: '☀️',
  sunset: '🌅',
  sunrise: '🌄',
  moon: '🌙',
  star: '⭐',
  cloud: '☁️',
  wind: '💨',
  storm: '⛈️',
  flood: '🌊',
  earthquake: '🌍',
  volcano: '🌋',
  rainbow: '🌈',
  fog: '🌫️',
  hail: '🌨️',
  hurricane: '🌀',
  tornado: '🌪️',
  drought: '🏜️',
  ice: '🧊',
  fire: '🔥',
  flame: '🔥',
  smoke: '💨',
  river: '🏞️',
  ocean: '🌊',
  sea: '🌊',
  lake: '🏞️',
  mountain: '⛰️',
  forest: '🌲',
  desert: '🏜️',
  island: '🏝️',
  beach: '🏖️',
  waterfall: '💧',
  cave: '🕳️',
  sky: '🌌',
  earth: '🌍',

  // Animals
  dog: '🐶',
  cat: '🐱',
  horse: '🐴',
  cow: '🐮',
  pig: '🐷',
  sheep: '🐑',
  goat: '🐐',
  chicken: '🐔',
  duck: '🦆',
  bird: '🐦',
  eagle: '🦅',
  owl: '🦉',
  parrot: '🦜',
  fish: '🐟',
  shark: '🦈',
  whale: '🐋',
  dolphin: '🐬',
  snake: '🐍',
  lion: '🦁',
  tiger: '🐯',
  bear: '🐻',
  elephant: '🐘',
  giraffe: '🦒',
  monkey: '🐒',
  rabbit: '🐰',
  fox: '🦊',
  wolf: '🐺',
  deer: '🦌',
  frog: '🐸',
  turtle: '🐢',
  butterfly: '🦋',
  bee: '🐝',
  ant: '🐜',
  spider: '🕷️',
  mouse: '🐭',
  rat: '🐀',
  camel: '🐪',
  zebra: '🦓',
  gorilla: '🦍',
  crocodile: '🐊',
  flamingo: '🦩',
  penguin: '🐧',
  octopus: '🐙',

  // Plants / Food
  apple: '🍎',
  banana: '🍌',
  orange: '🍊',
  grape: '🍇',
  strawberry: '🍓',
  watermelon: '🍉',
  lemon: '🍋',
  cherry: '🍒',
  pear: '🍐',
  peach: '🍑',
  mango: '🥭',
  pineapple: '🍍',
  coconut: '🥥',
  carrot: '🥕',
  potato: '🥔',
  tomato: '🍅',
  corn: '🌽',
  bread: '🍞',
  rice: '🍚',
  egg: '🥚',
  meat: '🥩',
  fish_food: '🐟',
  pizza: '🍕',
  burger: '🍔',
  cake: '🎂',
  coffee: '☕',
  tea: '🍵',
  milk: '🥛',
  water: '💧',
  juice: '🧃',
  beer: '🍺',
  wine: '🍷',
  vegetarian: '🥗',
  salad: '🥗',
  soup: '🍲',

  // Transport / Travel
  railway: '🚆',
  railroad: '🚆',
  train: '🚆',
  car: '🚗',
  bus: '🚌',
  bicycle: '🚲',
  bike: '🚲',
  motorcycle: '🏍️',
  airplane: '✈️',
  plane: '✈️',
  ship: '🚢',
  boat: '⛵',
  sail: '⛵',
  yacht: '🛥️',
  helicopter: '🚁',
  rocket: '🚀',
  taxi: '🚕',
  truck: '🚛',
  ambulance: '🚑',
  police: '🚓',
  subway: '🚇',
  tram: '🚊',
  road: '🛣️',
  bridge: '🌉',
  airport: '✈️',
  port: '⚓',
  map: '🗺️',
  travel: '✈️',
  journey: '🧳',
  trip: '🧳',
  luggage: '🧳',
  passport: '🛂',
  ticket: '🎫',
  hotel: '🏨',
  compass: '🧭',

  // People / Body
  person: '👤',
  man: '👨',
  woman: '👩',
  child: '👧',
  baby: '👶',
  family: '👪',
  friend: '👫',
  doctor: '👨‍⚕️',
  nurse: '👩‍⚕️',
  teacher: '👩‍🏫',
  student: '👨‍🎓',
  police_person: '👮',
  farmer: '👨‍🌾',
  chef: '👨‍🍳',
  artist: '👨‍🎨',
  scientist: '👨‍🔬',
  tailor: '🧵',
  dressmaker: '🪡',
  sailor: '⚓',
  pilot: '👨‍✈️',
  soldier: '💂',
  king: '👑',
  queen: '👑',
  heart: '❤️',
  hand: '✋',
  eye: '👁️',
  ear: '👂',
  nose: '👃',
  mouth: '👄',
  brain: '🧠',
  bone: '🦴',

  // Clothing
  shirt: '👕',
  dress: '👗',
  hat: '🎩',
  shoe: '👟',
  boot: '👢',
  bag: '👜',
  backpack: '🎒',
  glasses: '👓',
  ring: '💍',
  crown: '👑',
  cloth: '🧶',
  needle: '🧵',
  thread: '🧵',
  jacket: '🧥',
  coat: '🧥',
  scarf: '🧣',
  gloves: '🧤',
  socks: '🧦',

  // Home / Objects
  home: '🏠',
  house: '🏠',
  door: '🚪',
  window: '🪟',
  bed: '🛏️',
  chair: '🪑',
  table: '🪑',
  key: '🔑',
  lock: '🔒',
  phone: '📱',
  computer: '💻',
  television: '📺',
  tv: '📺',
  radio: '📻',
  camera: '📷',
  book: '📚',
  pen: '🖊️',
  pencil: '✏️',
  paper: '📄',
  letter: '✉️',
  clock: '🕐',
  lamp: '💡',
  candle: '🕯️',
  knife: '🔪',
  fork: '🍴',
  spoon: '🥄',
  plate: '🍽️',
  cup: '☕',
  glass: '🥛',
  box: '📦',
  bag_obj: '🛍️',
  calendar: '📅',
  money: '💰',
  coin: '🪙',
  wallet: '👛',
  gift: '🎁',
  balloon: '🎈',
  flag: '🚩',
  mirror: '🪞',
  broom: '🧹',
  hammer: '🔨',
  scissors: '✂️',
  pin: '📌',
  magnifying: '🔍',
  'magnifying glass': '🔍',
  telescope: '🔭',
  microscope: '🔬',
  needle_tool: '🪡',

  // Nature objects
  flower: '🌸',
  rose: '🌹',
  tree: '🌲',
  leaf: '🍃',
  mushroom: '🍄',
  seed: '🌱',
  grass: '🌿',
  cactus: '🌵',
  bamboo: '🎋',
  rock: '🪨',
  gem: '💎',
  diamond: '💎',
  pearl: '🪸',
  shell: '🐚',
  wave: '🌊',

  // Places / Buildings
  school: '🏫',
  hospital: '🏥',
  bank: '🏦',
  shop: '🏪',
  store: '🏬',
  restaurant: '🍽️',
  library: '📚',
  museum: '🏛️',
  church: '⛪',
  mosque: '🕌',
  castle: '🏰',
  prison: '🏛️',
  factory: '🏭',
  farm: '🚜',
  stadium: '🏟️',
  theater: '🎭',
  cinema: '🎬',
  park: '🌳',
  garden: '🌷',
  market: '🛒',
  office: '🏢',
  tower: '🗼',
  lighthouse: '🏮',
  temple: '⛩️',

  // Sports / Activities
  football: '⚽',
  soccer: '⚽',
  basketball: '🏀',
  tennis: '🎾',
  baseball: '⚾',
  volleyball: '🏐',
  swimming: '🏊',
  running: '🏃',
  cycling: '🚴',
  boxing: '🥊',
  wrestling: '🤼',
  race: '🏁',
  gym: '🏋️',
  yoga: '🧘',
  dance: '💃',
  music: '🎵',
  singing: '🎤',
  guitar: '🎸',
  piano: '🎹',
  drum: '🥁',
  violin: '🎻',
  sport: '🏅',
  medal: '🏅',
  trophy: '🏆',
  game: '🎮',
  chess: '♟️',
  puzzle: '🧩',

  // Emotions / States
  happy: '😊',
  sad: '😢',
  angry: '😠',
  love: '❤️',
  fear: '😱',
  surprise: '😮',
  laugh: '😂',
  cry: '😢',
  smile: '😊',
  bored: '😒',
  tired: '😴',
  sick: '🤒',
  healthy: '💪',
  strong: '💪',
  weak: '😔',
  brave: '🦁',
  shy: '😳',
  excited: '🎉',
  proud: '😤',
  calm: '😌',
  stress: '😰',
  worry: '😟',

  // Abstract / Concepts
  idea: '💡',
  question: '❓',
  answer: '💬',
  problem: '⚠️',
  risk: '⚠️',
  danger: '⚠️',
  success: '✅',
  failure: '❌',
  time: '⏰',
  money_concept: '💵',
  wealthy: '💰',
  rich: '💰',
  poor: '😔',
  power: '⚡',
  knowledge: '📚',
  dream: '💭',
  truth: '✅',
  lie: '🤥',
  secret: '🤫',
  friendship: '🤝',
  peace: '☮️',
  war: '⚔️',
  freedom: '🗽',
  justice: '⚖️',
  law: '⚖️',
  religion: '🙏',
  science: '🔬',
  art: '🎨',
  culture: '🎭',
  history: '📜',
  future: '🔮',
  past: '📜',
  change: '🔄',
  growth: '📈',
  death: '💀',
  life: '🌱',
  birth: '👶',

  // Special / Cultural
  ramadan: '🌙',
  eid: '🌙',
  christmas: '🎄',
  birthday: '🎂',
  wedding: '💒',
  graduation: '🎓',
  party: '🎉',
  celebration: '🎊',
  prayer: '🙏',
  weekend: '🏖️',
  holiday: '🏖️',
  vacation: '✈️',
  adventure: '🧗',

  // Misc
  light: '💡',
  dark: '🌑',
  hot: '🌡️',
  cold: '🥶',
  big: '🔺',
  small: '🔹',
  fast: '⚡',
  slow: '🐢',
  new: '✨',
  old: '📜',
  clean: '✨',
  dirty: '🗑️',
  magic: '✨',
  mystery: '🔮',
  robot: '🤖',
  'make-believe': '🪄',
  imagination: '🪄',
  fairy: '🧚',
  dragon: '🐉',
  princess: '👸',
  prince: '🤴',
  knight: '⚔️',

  // Animals & Nature additions
  reptile: '🦎',
  lizard: '🦎',
  aquarium: '🐠',
  aviary: '🐦',
  enclosure: '🏞️',
  keeper: '🛡️',
  guard: '👮',
  presenter: '🎙️',
  host: '🎤',
  adopt: '👨‍👩‍👧',
  canoeing: '🚣',
  canoe: '🚣',
  possession: '📦',
  'treasured possession': '💎',
  treasured: '💎',
  brief: '⏱️',
  description: '📝',
  certain: '🎯',
  sure: '🎯',
  sentimental: '💖',
  'sentimental value': '💖',
  stereo: '🎧',
  'personal stereo': '🎧',
  equipped: '🧰',
  equipment: '🧰',
  enable: '✅',
  allow: '✅',
  simply: '✨',
  simple: '✨',
  disturb: '🚫',
  interrupt: '🚫',
  constant: '🔄',
  continuous: '🔄',
  companionship: '🤝',
  companion: '🤝',
  value: '💎',
  worth_item: '💎',
};

/**
 * Look up emoji for a word. Case-insensitive.
 * Returns empty string if no match (caller should not force an emoji).
 */
export function lookupEmoji(word: string): string {
  const key = word.toLowerCase().trim();
  return EMOJI_MAP[key] ?? '';
}

/**
 * Batch lookup for multiple words.
 * Returns only entries with a found emoji.
 */
export function batchLookupEmoji(words: string[]): Record<string, string> {
  const result: Record<string, string> = {};
  for (const word of words) {
    const emoji = lookupEmoji(word);
    if (emoji) result[word] = emoji;
  }
  return result;
}
